---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/DjinnS/argocd.git
    targetRevision: HEAD
    path: argocd-config/apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
